---

- name: "iptables rst setup"
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination: "{{groups.defender.0}}"
    tcp_flags:
      flags: RST
      flags_set: RST
    jump: DROP
