---
- name: Envoyer une requête POST avec Ansible
  hosts: localhost  # L'hôte cible où vous souhaitez exécuter le playbook
  gather_facts: no  # Ne collectez pas d'informations sur l'hôte

  tasks:
    - name: Envoyer la requête POST
      uri:
        url: "http://192.168.56.2:5000/form"
        method: POST
        body_format: json  # Format des données à envoyer (dans ce cas, JSON)
        body:
          email: valeur
          pwd: autre_valeur
        status_code: 200  # Code d'état HTTP attendu en réponse
      register: result  # Stocker la réponse dans la variable result

    - name: Afficher la réponse
      debug:
        var: result
