---

- name: "install pip package"
  include: "pip-install.yml"
  when: pip_install|default(False)|bool

- name: "install scapy"
  apt:
    name: "python3-scapy"
    state: latest 
    install_recommends: yes
